name: Schedule Workflow importer Update

on:
 schedule:
   - cron: '*/1 * * *'  # At every minute.

jobs:
  update-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Script
        run: python .github/workflows/workflowimporter.py
        env:
          GITHUB_TOKEN: ${{ secrets.AUTO_ASSISTER_PAT }}
          GITHUB_ORG: 'GuineaBot3Labs'
